listeners:
  -
    address: "10.4.9.36"
    port: 9000
    https: false
  -
    address: "127.0.0.1"
    port: 9000
    https: false
db_clients:
  -
    name: jamd
    rdbms: postgresql
    host: "10.4.9.58"
    port: 5432
    dbname: jamd
    user: mojave
    password: 12345678
